### ISSUE TITLE
Investigate using Promises for async specs

### ISSUE THREAD

**Issue by adambeynon** [opal/opal-rspec#17]
Instead of:

```ruby
async 'HTTP requests should work' do
  HTTP.get('/users/1.json') do |res|
    run_async {
      expect(res).to be_ok
    }
  end
end
```

We could use:

```ruby
async 'HTTP requests should work' do
  HTTP.get('/users/1.json').then do |res|
      expect(res).to be_ok
  end
end
```

Basically, if the example block returns a Promise, then instead of the inner `run_async` block, the spec runner can just wait on the Promise to resolve or reject, and then handle it accordingly.

**Comment by ryanstout** [comment]
So I hate when people +1 issues/PR's, but here we go:

+1

**Comment by wied03** [comment]
I'm not sure it's the best approach, but I'm working on a branch I could turn into a PR here: https://github.com/wied03/opal-rspec/tree/opal-0.8-other/rspec31_async_fix

what works:
* Basic runner that uses promises along with example_group monkey patches and and a new AsyncExample class
* Test failures show up properly in results instead of uncaught exceptions (kind of a hack, but already had to do this with RSpec 3.1/lack of diff support for fail_with anyways)

I still need to get:
* example hierarchy working properly
* pending/skipped within the example working
* Support an async subject and/or example return value as you mention above so that the 'done' stuff is not necessary
* Ensure other specs besides async_spec.rb work (and all of the other async specs I'm toggling on and off right now as I test)
* See if there is a better way to test my work via CI besides manual inspection (test the test framework)

**Comment by ryanstout** [comment]
@wied03 awesome, that would really help me out a lot :-)  best of luck on it.  Thanks

**Comment by wied03** [comment]
Here's an update on that branch:

What works:
* If the example returns a promise, the runner waits for that promise to complete before continuing, example code from the checked in+pushed specs:
```
async 'matcher succeeds properly' do
    promise = Promise.new
    delay 1 do
      1.should == 1
      promise.resolve
    end
    promise
end
```
* Example group hierarchy working properly
* Pending/skipped within the example working
* Ensured other specs besides async_spec.rb work (and all of the other async specs I'm toggling on and off right now as I test)
* Added a basic Rake task that wraps the opal:spec test and ensures that we fail when we're supposed to and checks to make sure the right tests failed. This is kind of rudimentary I know, but before this, there was no way to verify that opal-rspec was failing when it should
* Test failures show up properly in results instead of uncaught exceptions (kind of a hack, but already had to do this with RSpec 3.1/lack of diff support for fail_with anyways)
* Basic runner that uses promises along with example_group monkey patches and and a new AsyncExample class

I still need to:
* Support an async subject

**Comment by ryanstout** [comment]
@wied03 so I thought I would ask this since your in the code right now.  Is there any possibility of not needing to use ```async``` (and just using ```it```)  My main issue is I need to run the same specs in both mri and opal.  I could just patch rspec when its running on mri to add async, but it would be great if it could work either way.  Thanks, keep up the good work :-)

**Comment by wied03** [comment]
@ryanstout - There is certainly appeal in doing that. I guess it depends how invasive we should be re: monkey patching RSpec. It's already invasive though to do what I've done, so not going further because it would be invasive might be a hollow argument.

@adambeynon  or @elia - any opinions?

**Comment by wied03** [comment]
The more I look at this, to get async before/subject working how it should (and I would consider those important), it might be easier just to go ahead and make 'it' run async by default. Otherwise there is 2 of everything with a mix, etc. and that's even more confusing

**Comment by wied03** [comment]
I've gone ahead and converted stuff to be async aware by default. I've added additional specs and have more of an understanding of promises, so I've been able to simplify my modifications. A little more work needs to be done before it's ready for a test drive

**Comment by wied03** [comment]
New branch of code is @ https://github.com/wied03/opal-rspec/tree/opal-0.8-other/rspec31_async_subject, almost done

**Comment by ryanstout** [comment]
@wied03 nice work :-)

**Comment by wied03** [comment]
https://github.com/opal/opal-rspec/pull/21

**Comment by wied03** [comment]
@ryanstout @adambeynon - This is in master now, so this issue can probably be closed

**Comment by elia** [comment]
:+1:
