### ISSUE TITLE
issues with opal 0.10.0

### ISSUE THREAD

**Issue by cj** [opal/opal-rspec#59]
When running you get `NoMethodError: undefined method `dynamic_require_severity=' for Opal::Processor:Class`.

`Opal.config.missing_require_severity` needs to be set instead.  To allow older version of opal, we might want to check which version of opal is running and set the correct one here https://github.com/opal/opal-rspec/blob/master/lib/opal/rspec.rb#L14

**Comment by wied03** [comment]
@cj - Not sure what version you're running but we don't support opal 0.10 yet. The opal-rspec 0.5 gemspec should prevent you from using it with 0.10 actually.

The changes you refer to (and other work that's still in progress) have already been made in master. We still have some more work to do before we have a release ready for 0.10 though.

**Comment by wied03** [comment]
@cj - Do you mind sharing what version of opal-rspec you tried to do this with?

**Comment by cj** [comment]
the latest version 0.5.0 :)

**Comment by wied03** [comment]
@cj - I suppose the most important thing to say is we are working on it. Just a few recent commits (some made by me fixing other issues actually) to opal 0.10 caused master of this repo to stop working. We should have it working shortly though.

I'm still curious how the opal-rspec 0.5 gemspec, which requires < opal 0.10 is working on your setup. Perhaps it considers the opal 0.10 beta to be less than opal 0.10 and that's why it allows you to install it.
