### ISSUE TITLE
how to require gem or a source file ?

### ISSUE THREAD

**Issue by catmando** [opal/opal-rspec#62]
I am testing a gem (react.rb) and in the tests I want to use opal-jquery

simply putting require 'opal-jquery' in the spec_helper.rb does not work (I have tried many combinations) and yes the opal-jquery gem is listed as a development dependency.

Likewise I want to put the sources for react.js in the gem, and then pull them in, during rspec testing, but again it doesn't want to work.

So if I have a file:  lib/sources/react_v13.js,   I assume that I can pull this in doing:  
require 'reactive-ruby/sources/react_v13'

The error I get is like this:

Sprockets::FileNotFound: couldn't find file 'opal-jquery' with type 'application/javascript'

Thanks in advance

**Comment by wied03** [comment]
Are you using the Rake task? Did you call Opal.use_gem from the Rakefile?
It sounds like a load path issue. I use jquery in my tests all the time.

sent from my mobile device
On May 27, 2016 22:07, "Mitch VanDuyn" <notifications@github.com> wrote:

I am testing a gem (react.rb) and in the tests I want to use opal-jquery

simply putting require 'opal-jquery' in the spec_helper.rb does not work (I
have tried many combinations) and yes the opal-jquery gem is listed as a
development dependency.

Likewise I want to put the sources for react.js in the gem, and then pull
them in, during rspec testing, but again it doesn't want to work.

So if I have a file: lib/sources/react_v13.js, I assume that I can pull
this in doing:

require 'reactive-ruby/sources/react_v13'

The error I get is like this:

Sprockets::FileNotFound: couldn't find file 'opal-jquery' with type
'application/javascript'

Thanks in advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opal/opal-rspec/issues/62>, or mute the thread
<https://github.com/notifications/unsubscribe/AASIo5eebAKyHj8S1h9pYzmHl9rF9gs-ks5qF79kgaJpZM4Io_Rj>
.

**Comment by wied03** [comment]
If you're using Rails but not using opal-rails, then you'd do something like this (I have 2 spec directories, thus the shared reference):
```ruby
Opal::RSpec::RakeTask.new('opal:spec' => :environment) do |server, task|
  app = Rails.application
  task.files = FileList[
      app.root.join('spec/javascripts/**/*_spec{,.js}.{rb,opal}'),
      app.root.join('spec/shared/**/*_spec{,.js}.{rb,opal}')
  ]
  task.default_path = 'spec/javascripts'
  app.assets.paths.each { |p| server.append_path p }
  %w(spec/javascripts spec/shared).each { |p| server.append_path p }
end
```
The only magic here is the app.assets line, which takes the Rails sprockets load paths (already populated via `Bundle.require` to force each GEM to add itself to the load path and my `opal.rb` initializer, which adds the Opal load paths to sprockets/Rails).

I'm not sure what the latest is with opal-rails since I've been working on other stuff.

**Comment by catmando** [comment]
thanks - I did not try your suggestion, instead I ended up doing this:
```ruby
# in reactive-ruby.rb 
...
Opal.append_path File.expand_path('../sources/', __FILE__).untaint
```

Once I did this everything go better

**Comment by wied03** [comment]
Hopefully this clarifies a little - https://github.com/opal/opal-rspec/commit/7e9a7abfeab7517c3662aff26f203c31eabdc255

**Comment by catmando** [comment]
thanks
