### ISSUE TITLE
Opal::RSpec::RakeTask

### ISSUE THREAD

**Issue by usergenic** [opal/opal-rspec#67]
References Net::HTTP at https://github.com/opal/opal-rspec/blob/master/lib/opal/rspec/rake_task.rb#L47

This causes a const-missing error unless you add require 'net/http' in your Rakefile.  Maybe just put that require in the rake_task.rb where it belongs?

**Comment by wied03** [comment]
Good catch. Thanks. I need to get back to work on this soon!

**Comment by wied03** [comment]
@usergenic - What version of Ruby were you using?

It should absolute be required and I have no idea why (it has been a long week) but for some reason it does not give me that error. I'm trying to replicate this with a test (see https://github.com/opal/opal-rspec/blob/bugs/http_require/Rakefile#L27-L32) before I fix it so that it does not regress.

We're not using `Bundler.require` anywhere so not sure why it's working for me without the `require`.

**Comment by usergenic** [comment]
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`

**Comment by elia** [comment]
seems it has been fixed a long time ago 😄
