### ISSUE TITLE
`expect_any_instance_of` is not working when using opal master

### ISSUE THREAD

**Issue by zetachang** [opal/opal-rspec#68]
An example spec like below won't work. 

```ruby
describe "Example1" do
  it "should work" do
    class Foo
      def bar; end
    end
    expect_any_instance_of(Foo).to receive(:bar)
    Foo.new.bar
  end
end
```

No error but an assertion failure message is shown

```
Exactly one instance should have received the following message(s) but didn't: bar
```

I've setup a repo for reproducing this issue. https://github.com/zetachang/opal-rspec-opal-11-dev-issues

**Comment by wied03** [comment]
Yeah. That one has been on the limitation list for a while.

sent from my mobile device

**Comment by zetachang** [comment]
Yeah, I know it's listed as **unstable** API, but it works (at least in my use case) using latest release of opal (0.10). Wondering if this is a regression of opal?

**Comment by wied03** [comment]
It's been so long since I've had time to work on this that I have no idea.

sent from my mobile device

**Comment by zetachang** [comment]
Done bisect against opal, and it looks like the breakage is introduced by https://github.com/opal/opal/commit/e1ca27aa.

**Comment by elia** [comment]
opal-rspec has now clear version targets: 
- 0.6.x is for opal 0.10.x
- 0.7.x is for opal 0.11.x (yet to be released)
- master is always an adventure 😄 but specs in 0.7 are very well organized and we have a much better test matrix now that uses original RSpec specs

I'll close the issue since the missing features are tracked by the upstream specs we run. 👍
