### ISSUE TITLE
Can you release a new version?

### ISSUE THREAD

**Issue by pocke** [opal/opal-rspec#81]
I'd like to use opal-rspec with Opal v1 in [Ovto](https://github.com/yhara/ovto), but It cannot.
Because the published version of opal-rspec restrict Opal version.

It looks relaxed by https://github.com/opal/opal-rspec/commit/6805d15131d65852264919165977090d42920876

Could you release a new version that includes the relaxing?

ref https://github.com/yhara/ovto/pull/9

**Comment by elia** [comment]
@pocke sure, I'll try to have that ready for tomorrow

**Comment by elia** [comment]
@pocke I've just released [v0.8.0.alpha1](https://rubygems.org/gems/opal-rspec/versions/0.8.0.alpha1), has no guarantees to work on Opal v1.

Also I pushed the WIP on Opal v1 in [this branch](https://github.com/opal/opal-rspec/pull/82), I don't plan to work on it soon, so if you want to give it a try that's more than welcome 🙂

_I'll close the issue, since now we have #82 to represent the task_

**Comment by pocke** [comment]
Thanks for the releasing!
I'll try using it.
